essays_link = [
    # Poetry Articles
    # "https://rezonodwes.com/?p=365826",
    # "https://rezonodwes.com/?p=366397",
    # "https://rezonodwes.com/?p=235178",
    # "https://rezonodwes.com/?p=235273",
    # "https://rezonodwes.com/?p=368689",
    # "https://rezonodwes.com/?p=305587",
    # "https://rezonodwes.com/?p=306940",
    # "https://rezonodwes.com/?p=309708",
    # "https://rezonodwes.com/?p=283486",
    # "https://rezonodwes.com/?p=263359",
    # "https://rezonodwes.com/?p=257293",
    # "https://rezonodwes.com/?p=365479",
    # "https://rezonodwes.com/?p=248675",
    # "https://rezonodwes.com/?p=240845",
    # "https://rezonodwes.com/?p=364722",
    # "https://rezonodwes.com/?p=362645",
    # "https://rezonodwes.com/?p=368248",
    # "https://rezonodwes.com/?p=348667",
    # "https://rezonodwes.com/?p=327866",
    # "https://rezonodwes.com/?p=327689",
    # "https://rezonodwes.com/?p=327267",
    # "https://rezonodwes.com/?p=327049",
    # "https://rezonodwes.com/?p=333706",
    # "https://rezonodwes.com/?p=326783",
    # "https://rezonodwes.com/?p=317181",
    # "https://rezonodwes.com/?p=317061",
    # "https://rezonodwes.com/?p=316721",
    # "https://rezonodwes.com/?p=326982",
    # Poetry Collections Published as Essays
    # "https://www.potomitan.info/vedrine/poesies.php#chinwa",
    # "https://www.potomitan.info/vedrine/elksyon.html",
    # "https://www.potomitan.info/vedrine/vodou.php",
    # "https://www.potomitan.info/vedrine/lekti.php",
    # "https://www.potomitan.info/vedrine/espwa.html",
    # "https://www.potomitan.info/vedrine/konsyantize.php",
    # "https://www.potomitan.info/vedrine/oryantasyon.php",
    # "https://www.potomitan.info/vedrine/maryaj.php",
    # "https://www.potomitan.info/vedrine/dezyem.php",
    # "https://www.potomitan.info/vedrine/pawoli.php",
    # "https://www.potomitan.info/vedrine/50.php",
    # "https://www.potomitan.info/vedrine/demen.php",
    # "https://www.potomitan.info/vedrine/malis.php",
    # "https://www.potomitan.info/vedrine/diskou.php",
    # "https://www.potomitan.info/vedrine/estenvil.php",
    # "https://www.potomitan.info/vedrine/pwoveb.php",
    # "https://www.potomitan.info/vedrine/pati.php",
    # "https://www.potomitan.info/vedrine/teknik.php",
    # "https://www.potomitan.info/vedrine/okipasyon.php",
    # "https://www.potomitan.info/vedrine/politik.php",
    # "https://www.potomitan.info/vedrine/kandida_2006.php",
    # "https://www.potomitan.info/vedrine/dis_pwen-k.php",
    # "https://www.potomitan.info/vedrine/enfomatize-01.php",
    # "https://www.potomitan.info/vedrine/pwogre.php",
    # "https://www.potomitan.info/ayiti/seisme_2021d.php",
    # "https://www.potomitan.info/vedrine/kapital.php",
    # "https://www.potomitan.info/vedrine/rekonstriksyon.php",
    # "https://www.potomitan.info/vedrine/fanm.html",
    # "https://www.potomitan.info/vedrine/temporada.php",
    "https://www.potomitan.info/ayiti/lafontan/agasou.php",
    "https://www.potomitan.info/ayiti/lafontan/bondye.php",
    "https://www.potomitan.info/ayiti/lafontan/andeyo.php",
    "https://www.potomitan.info/ayiti/lafontan/annela.php",
    # "https://www.potomitan.info/divers/nwel_2012a.php#Dumafis",
    # "https://www.potomitan.info/ayiti/lafontan/ayiti.php",
    "https://www.potomitan.info/ayiti/lafontan/jou.php",
    "https://www.potomitan.info/ayiti/lafontan/chas.php",
    "https://www.potomitan.info/ayiti/lafontan/etwal.php",
    "https://www.potomitan.info/ayiti/lafontan/fleret.php",
    "https://www.potomitan.info/ayiti/lafontan/nanchon.php",
    "https://www.potomitan.info/ayiti/lafontan/tan2.php",
    "https://www.potomitan.info/ayiti/lafontan/vayan.php",
    # "https://www.potomitan.info/ayiti/lafontan/dlo.php",
    "https://www.potomitan.info/ayiti/lafontan/jistis.php",
    "https://www.potomitan.info/ayiti/lafontan/kontinyite.php",
    "https://www.potomitan.info/ayiti/lafontan/lafrik.php",
    "https://www.potomitan.info/ayiti/lafontan/lamlamdlo.php",
    "https://www.potomitan.info/ayiti/lafontan/imigran.php",
    "https://www.potomitan.info/ayiti/lafontan/doudous.php",
    "https://www.potomitan.info/ayiti/lafontan/met.php",
    "https://www.potomitan.info/ayiti/lafontan/g.php",
    "https://www.potomitan.info/ayiti/lafontan/papados.php",
    "https://www.potomitan.info/ayiti/lafontan/odela.php",
    "https://www.potomitan.info/ayiti/lafontan/ola.php",
    # "https://www.potomitan.info/ayiti/lafontan/pouri.php",
    "https://www.potomitan.info/ayiti/lafontan/ginen.php",
    "https://www.potomitan.info/ayiti/lafontan/pititfi.php",
    "https://www.potomitan.info/ayiti/lafontan/liberasyon.php",
    "https://www.potomitan.info/ayiti/lafontan/pwezi.php",
    "https://www.potomitan.info/ayiti/lafontan/retou.php",
    "https://www.potomitan.info/ayiti/lafontan/sak.php",
    "https://www.potomitan.info/ayiti/lafontan/tanmtanm.php",
    "https://www.potomitan.info/ayiti/lafontan/tulsi.php",
    "https://www.potomitan.info/ayiti/lafontan/nasyon.php",
    "https://www.potomitan.info/ayiti/lafontan/veye.php",
    # "https://www.potomitan.info/ayiti/lafontan/altemond.php",
    "https://www.potomitan.info/ayiti/lafontan/bombe.php",
    "https://www.potomitan.info/ayiti/lafontan/depasmman.php",
    # "https://www.potomitan.info/ayiti/lafontan/gran_rivye.php",
    # "https://www.potomitan.info/ayiti/lafontan/platon.php",
    "https://www.potomitan.info/ayiti/lafontan/rekonstriksyon.php",
    # "https://www.potomitan.info/ayiti/lafontan/agangou.php",
    "https://www.potomitan.info/ayiti/lafontan/ezili.php",
    "https://www.potomitan.info/ayiti/lafontan/manmi.php",
    # "https://www.potomitan.info/ayiti/lafontan/manifes.php",
    "https://www.potomitan.info/ayiti/lafontan/tan.php",
    "https://www.potomitan.info/ayiti/lafontan/ogounati.php",
    # "https://www.potomitan.info/ayiti/lafontan/pale.php",
    # "https://www.potomitan.info/ayiti/lafontan/politik.php",
    # "https://www.potomitan.info/ayiti/lafontan/kanpe.php",
    # "https://www.potomitan.info/ayiti/lafontan/endepandans.php",
    # "https://www.potomitan.info/ayiti/lafontan/viv.php",
        




]
