essays_titles = [
    # "Ala traka pou demokrasi",
    # "Anpàn mo",
    # "Ayisyen ak Chinwa",
    # "Ayisyen, sispann pran lòd nan men zòt !",
    # "Ayisyen, yon metis",
    # "Ayiti bezwen dyaspora",
    # "Ayiti nan fen ventyèm syèk",
    # "Ayiti pèpèrize",
    # "Ayiti pou Ayisyen",
    # "Babay lekòl mwen an",
    # "Bòn anivèsè",
    # "Bò Oseyan an",
    # "Chalbari dèyè save raketè!",
    # "De flè nan jaden lavi",
    # "Dènye Lend",
    # "Deskripsyo",
    # "Dezyèm endepandan",
    # "Diskou yon kandida tafyat",
    # "Divò",
    # "Douz liy pou l",
    # "Egzamen pou kandida alaprezidans",
    # "Eleksyon konfizyon",
    # "Epi solèy la leve Ayiti",
    # "Èske n ap kontinye tann Papa Leta?",
    # "Èske nou gen desandan?",
    # "Esprime w!",
    # "Fanm Ayiti",
    # "Fanm kreyòl",
    # "Fanm lakay",
    # "Fanm marabou",
    # "Fènwa ak klete an 1991",
    # "Filalang lanmou",
    # "File",
    # "File se yon lotri",
    # "Flè sovay",
    # "Fòk sa fini!",
    # "Si w renmen Ayiti",
    # "Ann pale de bwa ak fri Ayiti",
    # "Pye mango",
    # "Pye labapen ak pye veritab",
    # "Pye zaboka",
    # "Defann mwen m ap defann ou zaboka",
    # "Pye kokoye",
    # "Nègès ki fè bote rivaj mwen yo",
    # "Pye Palmis",
    # "Pyebwa libète",
    # "Pye kayimit",
    # "Fanm marabou jansiv vyolèt",
    # "Pye sapoti",
    # "Sapoti ou dous",
    # "Pye kachiman",
    # "Lè m monte yon pye kachiman",
    # "Pye kakawo",
    # "Eske Ayiti reyèlman bezwen yon akademi kreyòl?",
    # "ABRAAM DI SÈTASE !",
    # "Divalye, Aristid: menm kout baton",
    # "Tout moun ki kont pwogrè rechèch",
    # "Viv kreyòl!",
    # "Èske yon pwogram miltileng pral solisyone vrè pwoblèm lekòl Ayiti ?",
    # "Lèt Wyclef voye bay «Ayisyen Dyaspora ki konsène»",
    # "Yon moun ki rejte kilti l",
    # "Baay Florida sa a genlè se yon waytouke k ap fè politisyen chimè",
    # "Chak grenn ayisyen enpòtan pou devlopman Ayiti",
    # "Bòn chans a pwochen prezidan Ayiti a!",
    # "Kèk sipètisyon nan kilti ayisyen",
    # "Kòmantè sou ‘demokrasi’",
    # "AYITI: BABAY A YON LAME REPRESIF",
    # "Kèk kòmantè enpòtan sou itilizasyon kreyòl an(n) Ayiti, estrè nan yon chita pale ak André Vilaire Chéry",
    # "Ki fiti jenès la Ayiti ?",
    # "Kisa n ka fè pou ede Ministè Edikasyon Nasyonal Ayiti ?",
    # "Sou lang matènèl Ayiti ak Frankofoni",
    # "Nòt pou 'distribitè' ak 'mezondedisyon liv kreyòl'",
    # "Diskou Bataille de Vertière",
    # "Florida: ou pale kreyòl?",
    # "Ayiti ak otodestriksyon",
    # "Jèn Ayisyen ak Lidèchip",
    # "KOMANTÈ - Jèn Ayisyen ak Lidèchip",
    # "Refleksyon sou 7 Fevriye 2019 : 33 ane apre Rejim Duvalier a tonbe",
    # "Lazil, yon komin ki ka vin yon atraksyson touristik Ayiti",
    # "FOWÒM MOUN Lazil",
    # "Richès kiltirèl Ayiti: yon min ki poko esplwate",
    # "Kilès ki ta responsab pwoblèm Ayiti yo?",
    # "Resèt pou kèk Pla Ayisyen",
    # "Swaf pou yon sosyete ayisyèn k ap fòme sitwayen l",
    # "Wyclef Jean ap chèche yon solisyon lapè pou Ayiti atravè dyalòg",
    # "Relijyon ak eksplwatasyon sa k pi ba yo",
    # "ÈSKE W SE YON AYISYEN KI FYÈ ?",
    # "D.P.M-KANNTÈ : YON PON ANT FIKSYON AK REYALITE",
    # "Eklèsisman  ak Demistifikasyon Tontongi nan liv li a",
    # "Pou yon frankofoni vivan e popilè",
    # "Nòt - Pou yon frankofoni vivan e popilè",
    # "Ayiti: Pou yon edikasyon pratik lè vandredi",
    # "Revolisyon Ayiti : Benefis Pou Kilès ?",
    # "Mennen koulèv la lekòl se youn, fè l chita se de",
    # "Ki tip lame Ayiti bezwen ?",
    # "KISA AYITI KA BENEFISYE DE KOWALISYON KANDIDA ALAPREZIDANS YO LAVÈY ELEKSYON PREZIDANSYÈL?",
    # "Viv oubyen aba lame: pawòl tafya kèk ayisyen",
    # "Sijè pou debat nan Medya Ayisyen nan Dyaspora",
    # "Men l anlè a l ap vini",
    # "Malis ak bèf Nonk Bouki",
    # "Jipon nwa a",
    # # "SEZON SECHRÈS AYITI - NÒT POU LEKTÈ А",
    # # "SEZON SECHRÈS AYITI - PWOLÒG",
    # # "SEZON SECHRÈS AYITI - CHAPIT I",
    # # "SEZON SECHRÈS AYITI - CHAPIT 2",
    # # "SEZON SECHRÈS AYITI - CHAPIT 3",
    # # "SEZON SECHRÈS AYITI - CHAPIT 4",
    # # "SEZON SECHRÈS AYITI - CHAPIT 5",
    # # "SEZON SECHRÈS AYITI - CHAPIT 6",
    # # "SEZON SECHRÈS AYITI - CHAPIТ 7",
    # # "SEZON SECHRÈS AYITI - CHAPIT 8",
    # # "SEZON SECHRÈS AYITI - CHAPIТ 9",
    # "FÒ SA FINI!",
    # "DEZYÈM ENDEPANDANS",
    # "SEZON WOUJ",
    # "RÈV POU YON MANMAN AN DANJE",
    # "AYITI POU AYISYEN",
    # "EPI SOLÈY LA LEVE AYITI",
    # "LÈ AYITI TE AYITI",
    # "MONTRE M PIТО",
    # "Aselòm fè yon kanpe la jodiya sou aktivite kiltirèl yo.",
    # "Gason Poem",
    # "Onèl kòmante sou lanmò a ak plis detay.",
    # "Sonson mansyone kijan I kite Sendomeng.",
    # "Aselòm sou pwen pou I al nan yon reyinyon.",
    # "Sonson monchè, se konsa bagay yo ye?",
    # "Konpè ou Dyelifèt.",
    # "Nouvèl lanmò Kenòl, lòt krim zenglendo yo fè, ak lanmò Tonton Pyè fè Sonson sezi.",
    # "Ay! Ou pa nan dòmi Sonson! Konpliman monchè! Kontinye travay byen konsa!",
    "Fè jistis reye",
    "Lekti menm paj istwa",
    "Gran Rivyè Dinò, vil kote Dessalines leve kanpe pou tout Ayisyen viv Lib nan peyi Endepandan!",
    "Peyizaj Rivnòdè",
    "Gwòt de Platon",
    "Repiblik Ekstèminatris & Otoritè",
    "Kavman poem",
    "Toubiyon Ginen",
    "Konfliyans Kiltirèl",
    "Kanatsiohareke, ka on etid",
    "Konfliyans poem",
    "Kanpe nan Bwa",
    "Manifès Popilè",
    "Ayiti, yon Paj Listwa",
    "Manifès Popilè 2",
    "Ayiti Nèf",
    "Pale Fransè pa vle di lespri",
    "Istwa Kolektif",
    "Monte tèt dlo",
    "Krik! Krak?",
    "Pale Fransè pa vle di lespri 2",
    "Lekòl Mèveye osnon Ayisyen",
    "Politik Lari a",
    "Oun bann ak pakèt ewè",
    "Politik Lari a 2",
    "An konklizyon",
    "Sou kisa w kanpe?",
    "Jefò pran kontwòl zile a",
    "Dessalines kòm medyatè",
    "Mèveye elemantè a lekòl",
    "Do miwa",
    "Peyizan Bisantnè pito Milenè!",
    "Sou kisa w kanpe? 2",
    "Tè e Endepandans Mele",
    "Faz Devlopman",
    "Analiz final",
    "Viv Ayiti Lib e Endepandan",
    "Desalin e Preval",
    "Pouki tout tole la?",
    "Ale nan sosyete Ayisyen",
    "Analiz final 2",
    "On tan pouri poem",
    "Oti Nwel pasé poem",
    "Atibon Legba poem",
    "Nwèl katye popilè poem",
    "Nwèl ak joud'lan poem",
    "Si pa ta gen Nwèl poem",
    "Bolomnwel poem",
    "Chanté Nwèl poem",
    "Ayiti, N ap Pike Devan",
    "Kontèks kriz la",
    "Pwendvi Andojèn e Egzojèn",
    "Analiz final 3",
    "Jete dlo, nan non zanset yo, 22 Dawou",
    "An verite poem",
    "Brasè Poem",
    "Jean Watson Charles Poem",
    "Pou Edwidge Sylvain",
    "Yo di POem",
    "Man Klo pa la ankô",
    "Manman Kreyòl Poem",
    





]
