essays_link = [
    # Poetry Articles
    # "https://rezonodwes.com/?p=365826",
    # "https://rezonodwes.com/?p=366397",
    # "https://rezonodwes.com/?p=235178",
    # "https://rezonodwes.com/?p=235273",
    # "https://rezonodwes.com/?p=368689",
    # "https://rezonodwes.com/?p=305587",
    # "https://rezonodwes.com/?p=306940",
    # "https://rezonodwes.com/?p=309708",
    # "https://rezonodwes.com/?p=283486",
    # "https://rezonodwes.com/?p=263359",
    # "https://rezonodwes.com/?p=257293",
    # "https://rezonodwes.com/?p=365479",
    # "https://rezonodwes.com/?p=248675",
    # "https://rezonodwes.com/?p=240845",
    # "https://rezonodwes.com/?p=364722",
    # "https://rezonodwes.com/?p=362645",
    # "https://rezonodwes.com/?p=368248",
    # "https://rezonodwes.com/?p=348667",
    # "https://rezonodwes.com/?p=327866",
    # "https://rezonodwes.com/?p=327689",
    # "https://rezonodwes.com/?p=327267",
    # "https://rezonodwes.com/?p=327049",
    # "https://rezonodwes.com/?p=333706",
    # "https://rezonodwes.com/?p=326783",
    # "https://rezonodwes.com/?p=317181",
    # "https://rezonodwes.com/?p=317061",
    # "https://rezonodwes.com/?p=316721",
    # "https://rezonodwes.com/?p=326982",
    # Poetry Collections Published as Essays
    # "https://www.potomitan.info/vedrine/poesies.php#chinwa",
    # "https://www.potomitan.info/vedrine/elksyon.html",
    # "https://www.potomitan.info/vedrine/vodou.php",
    # "https://www.potomitan.info/vedrine/lekti.php",
    # "https://www.potomitan.info/vedrine/espwa.html",
    # "https://www.potomitan.info/vedrine/konsyantize.php",
    # "https://www.potomitan.info/vedrine/oryantasyon.php",
    # "https://www.potomitan.info/vedrine/maryaj.php",
    # "https://www.potomitan.info/vedrine/dezyem.php",
    # "https://www.potomitan.info/vedrine/pawoli.php",
    # "https://www.potomitan.info/vedrine/50.php",
    # "https://www.potomitan.info/vedrine/demen.php",
    # "https://www.potomitan.info/vedrine/malis.php",
    # "https://www.potomitan.info/vedrine/diskou.php",
    # "https://www.potomitan.info/vedrine/estenvil.php",
    "https://www.potomitan.info/vedrine/pwoveb.php",
    "https://www.potomitan.info/vedrine/pati.php",
    "https://www.potomitan.info/vedrine/teknik.php",
    "https://www.potomitan.info/vedrine/okipasyon.php",
    "https://www.potomitan.info/vedrine/politik.php",
    "https://www.potomitan.info/vedrine/kandida_2006.php",
    "https://www.potomitan.info/vedrine/dis_pwen-k.php",
    



]
