essays_titles = [
    "Ala traka pou demokrasi",
    "Anpàn mo",
    "Ayisyen ak Chinwa",
    "Ayisyen, sispann pran lòd nan men zòt !",
    "Ayisyen, yon metis",
    "Ayiti bezwen dyaspora",
    "Ayiti nan fen ventyèm syèk",
    "Ayiti pèpèrize",
    "Ayiti pou Ayisyen",
    "Babay lekòl mwen an",
    "Bòn anivèsè",
    "Bò Oseyan an",
    "Chalbari dèyè save raketè!",
    "De flè nan jaden lavi",
    "Dènye Lend",
    "Deskripsyo",
    "Dezyèm endepandan",
    "Diskou yon kandida tafyat",
    "Divò",
    "Douz liy pou l",
    "Egzamen pou kandida alaprezidans",
    "Eleksyon konfizyon",
    "Epi solèy la leve Ayiti",
    "Èske n ap kontinye tann Papa Leta?",
    "Èske nou gen desandan?",
    "Esprime w!",
    "Fanm Ayiti",
    "Fanm kreyòl",
    "Fanm lakay",
    "Fanm marabou",
    "Fènwa ak klete an 1991",
    "Filalang lanmou",
    "File",
    "File se yon lotri",
    "Flè sovay",
    "Fòk sa fini!",
    "Si w renmen Ayiti",
    "Ann pale de bwa ak fri Ayiti",
    "Pye mango",
    "Pye labapen ak pye veritab",
    "Pye zaboka",
    "Defann mwen m ap defann ou zaboka",
    "Pye kokoye",
    "Nègès ki fè bote rivaj mwen yo",
    "Pye Palmis",
    "Pyebwa libète",
    "Pye kayimit",
    "Fanm marabou jansiv vyolèt",
    "Pye sapoti",
    "Sapoti ou dous",
    "Pye kachiman",
    "Lè m monte yon pye kachiman",
    "Pye kakawo",
    "Eske Ayiti reyèlman bezwen yon akademi kreyòl?",
    "ABRAAM DI SÈTASE !",
    "Divalye, Aristid: menm kout baton",
    "Tout moun ki kont pwogrè rechèch",
    "Viv kreyòl!",
    "Èske yon pwogram miltileng pral solisyone vrè pwoblèm lekòl Ayiti ?",
    "Lèt Wyclef voye bay «Ayisyen Dyaspora ki konsène»",
    "Yon moun ki rejte kilti l",
    "Baay Florida sa a genlè se yon waytouke k ap fè politisyen chimè",
    "Chak grenn ayisyen enpòtan pou devlopman Ayiti",
    "Bòn chans a pwochen prezidan Ayiti a!",
    "Kèk sipètisyon nan kilti ayisyen",
    "Kòmantè sou ‘demokrasi’",
    "AYITI: BABAY A YON LAME REPRESIF",
    "Kèk kòmantè enpòtan sou itilizasyon kreyòl an(n) Ayiti, estrè nan yon chita pale ak André Vilaire Chéry",
    "Ki fiti jenès la Ayiti ?",
    "Kisa n ka fè pou ede Ministè Edikasyon Nasyonal Ayiti ?",
    "Sou lang matènèl Ayiti ak Frankofoni",
    "Nòt pou 'distribitè' ak 'mezondedisyon liv kreyòl'",
    "Diskou Bataille de Vertière",
    "Florida: ou pale kreyòl?",
    "Ayiti ak otodestriksyon",
    "Jèn Ayisyen ak Lidèchip",
    "KOMANTÈ - Jèn Ayisyen ak Lidèchip",
    "Refleksyon sou 7 Fevriye 2019 : 33 ane apre Rejim Duvalier a tonbe",
    "Lazil, yon komin ki ka vin yon atraksyson touristik Ayiti",
    "FOWÒM MOUN Lazil",
    "Richès kiltirèl Ayiti: yon min ki poko esplwate",
    "Kilès ki ta responsab pwoblèm Ayiti yo?",
    "Resèt pou kèk Pla Ayisyen",
    "Swaf pou yon sosyete ayisyèn k ap fòme sitwayen l",
    "Wyclef Jean ap chèche yon solisyon lapè pou Ayiti atravè dyalòg",
    "Relijyon ak eksplwatasyon sa k pi ba yo",
    "ÈSKE W SE YON AYISYEN KI FYÈ ?",
    "D.P.M-KANNTÈ : YON PON ANT FIKSYON AK REYALITE",
    "Eklèsisman  ak Demistifikasyon Tontongi nan liv li a",
    "Pou yon frankofoni vivan e popilè",
    "Nòt - Pou yon frankofoni vivan e popilè",
    "Ayiti: Pou yon edikasyon pratik lè vandredi",
    "Revolisyon Ayiti : Benefis Pou Kilès ?",
    "Mennen koulèv la lekòl se youn, fè l chita se de",
    "Ki tip lame Ayiti bezwen ?",
    "KISA AYITI KA BENEFISYE DE KOWALISYON KANDIDA ALAPREZIDANS YO LAVÈY ELEKSYON PREZIDANSYÈL?",
    "Viv oubyen aba lame: pawòl tafya kèk ayisyen",
    "Sijè pou debat nan Medya Ayisyen nan Dyaspora",
    


]
