essays_titles = [
    "Ala traka pou demokrasi",
    "Anpàn mo",
    "Ayisyen ak Chinwa",
    "Ayisyen, sispann pran lòd nan men zòt !",
    "Ayisyen, yon metis",
    "Ayiti bezwen dyaspora",
    "Ayiti nan fen ventyèm syèk",
    "Ayiti pèpèrize",
    "Ayiti pou Ayisyen",
    "Babay lekòl mwen an",
    "Bòn anivèsè",
    "Bò Oseyan an",
    "Chalbari dèyè save raketè!",
    "De flè nan jaden lavi",
    "Dènye Lend",
    "Deskripsyo",
    "Dezyèm endepandan",
    "Diskou yon kandida tafyat",
    "Divò",
    "Douz liy pou l",
    "Egzamen pou kandida alaprezidans",
    "Eleksyon konfizyon",
    "Epi solèy la leve Ayiti",
    "Èske n ap kontinye tann Papa Leta?",
    "Èske nou gen desandan?",
    "Esprime w!",
    "Fanm Ayiti",
    "Fanm kreyòl",
    "Fanm lakay",
    "Fanm marabou",
    "Fènwa ak klete an 1991",
    "Filalang lanmou",
    "File",
    "File se yon lotri",
    "Flè sovay",
    "Fòk sa fini!",
    "Si w renmen Ayiti",
    "Ann pale de bwa ak fri Ayiti",
    "Pye mango",
    "Pye labapen ak pye veritab",
    "Pye zaboka",
    "Defann mwen m ap defann ou zaboka",
    "Pye kokoye",
    "Nègès ki fè bote rivaj mwen yo",
    "Pye Palmis",
    "Pyebwa libète",
    "Pye kayimit",
    "Fanm marabou jansiv vyolèt",
    "Pye sapoti",
    "Sapoti ou dous",
    "Pye kachiman",
    "Lè m monte yon pye kachiman",
    "Pye kakawo",
]
